### ISSUE TITLE
map scrollwheel zoom

### ISSUE THREAD

**Issue by kodonnell** [nz-stefan/shiny_ufo_app#1]
Zoom control with scroll wheel? (Not present with Chrome.)

**Comment by nz-stefan** [comment]
Hm, seems to work for me. Will investigate further if I can reproduce the error.

**Comment by kodonnell** [comment]
chrome inspector messages on click:

> [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.

on scroll:

> shiny-server-client.js:282 Mon Jul 31 2017 14:19:23 GMT+1200 (New Zealand Standard Time) [DBG]: 1 message(s) discarded from buffer

**Comment by nz-stefan** [comment]
The problem seems to occur when you scroll the page first and then attempt to scroll in the map.

**Comment by nz-stefan** [comment]
Fixed in the latest commit.

**Comment by kodonnell** [comment]
Nice!
